import React from "react";
import Head from "next/head";
import NavbarBlock from "./blocks/NavbarBlock";

const HeaderBlock = () => {
	return (
		<>
			<Head>
				<title>Orka IT solutions</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="navbar-block">
				<NavbarBlock />
			</div>
		</>
	);
};

export default HeaderBlock;
